### ISSUE TITLE
unknown feature `proc_macro_span_shrink`

### ISSUE THREAD

**Issue by wang13245** [unibg-seclab/permissionsnoop#1]
![image](https://github.com/unibg-seclab/permissionsnoop/assets/112768820/7f6b70f1-e744-439d-a5b9-dffc2c7fa702)

**Comment by dariofad** [comment]
Hi wang13245,

I checked the issue and and can confirm it is associated with `proc-macro2 v1.0.59` and a specific version of Rust.
More details are shown here [proc-macro2 issue](https://github.com/rust-lang/rust/issues/113152).

Upgrading the toolchain to the latest version (`rustup update`) solves it (I tested with both  `rustc 1.71.1` and `1.71.0`).
Please let me know if you experience other errors.
